FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

# Copy source code (optional if mounting volumes, but good practice)
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
