FROM node:20.19-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci

# Copy source code (optional if mounting volumes, but good practice)
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
